### ISSUE TITLE
Remove outdated docs

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tillitis-key1#181] opened 2024-03-19 14:59 UTC
Some of the documentation under `docs` now lives in the Dev Handbook. Remove the probably outdated duplicates.

- Note that `boards.md` and `fpga.md` are not in Dev Handbook and probably shouldn't be. Perhaps they shouldn't even be in `system_description` and just under `docs`?
- Where do we put `docs/threat_model/threat_model.md`? It's currently both here and on the web site at Tillitis. Move to dev.tillitis.se?

**Comment by dehanj** [comment] 2024-11-11 12:16
Duplicate of https://github.com/tillitis/tillitis-key1/issues/274 ?

**Closed** 2024-11-11 17:29 UTC
Labels: documentation
